# Welcome to Jekyll!
title: AsociaciÃ³n La Buena Leche
email: labuenalecheasociacion@gmail.com
baseurl: ""
url: "https://labuenaleche.org"
gtag: UA-66444400-1
iban: ES88 0049 6742 54 2216337871

social:
  twitter: asociacionlbl
  facebook: AsociacionLaBuenaLeche
  instagram: labuenalecheasociacion
  blog: https://compartiendocrianza.blogspot.com/

markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-sitemap

assets:
  plugins:
    css: { autoprefixer: {} }
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

notice: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - Rakefile
  - Dockerfile
  - entrypoint.sh
  - docker-compose.yml
