volumes:
  bundle-volume:

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/jekyll
      - bundle-volume:/usr/local/bundle
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true
    entrypoint: [entrypoint]
    command: ["jekyll", "serve", "--host", "0.0.0.0"]

  bundle-volume:
    image: busybox
    volumes:
      - bundle-volume:/usr/local/bundle
